---
# defaults file for swift-proxy
swift_password: SWIFT_PASS
keystone_admin_password: ADMIN_PASS
admin_env:
  OS_PROJECT_DOMAIN_NAME: Default
  OS_USER_DOMAIN_NAME: Default
  OS_PROJECT_NAME: admin
  OS_USERNAME: admin
  OS_PASSWORD: "{{ keystone_admin_password }}"
  OS_AUTH_URL: "http://{{ groups['keystone'][0] }}:5000/v3/"
  OS_IDENTITY_API_VERSION: 3
  OS_IMAGE_API_VERSION: 2